
name: Update mirror

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        
    steps:
    - uses: actions/checkout@v2
      with:
        ref: gh-pages
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - uses: ko-Kore/publish@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TASK_NAME: 'Update mirror'
        TIMEZONE: 'Asia/Seoul'
        BRANCH_NAME: 'gh-pages'
    - run: npm run update pages docs 20 2000
    - run: npm run fullbuild indices docs
