
name: Update mirror

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: gh-pages
        submodules: recursive
    - uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
    - uses: ko-Kore/publish@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TASK_NAME: 'Update mirror'
        TIMEZONE: 'Asia/Seoul'
        BRANCH_NAME: 'gh-pages'
    - run: npm install
    - run: npm run update pages docs 20 2000
    - run: npm run fullbuild indices docs
